<?php
/** @var Nans\StoreLocator\Block\Widget\Map $block */
try {
    $apiUrl = $block->getApiUrl();
    $locations = $block->getLocationsJson();
} catch (Throwable $throwable) {
    echo $throwable->getMessage();

    return;
}
?>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "store_location": {
                    "component" : "Nans_StoreLocator/js/googlemap",
                    "locations" : <?php echo $locations ?>
                }
            }
        }
    }
}
</script>
<script>
    function initMap() {}
</script>
<script src="<?php echo $apiUrl; ?>&callback=initMap"></script>
<div id="map" style="<?php echo $block->getHeight() . $block->getWidth();?>" data-bind="scope: 'store_location'"></div>