<?php
/** @var Nans\StoreLocator\Block\Widget\Map $block */
try {
    $apiUrl = $block->getApiUrl();
    $locations = $block->getLocationsJson();
} catch (\Throwable $throwable) {
    echo $throwable->getMessage();

    return;
}
?>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "store_location": {
                    "component" : "Nans_StoreLocator/js/google_map",
                    "locations" : <?php echo $locations ?>,
                    "description_pattern" : "<?php echo $block->getDescription(); ?>"
                }
            }
        }
    }
}
</script>
<script>
    function initMap() {}
</script>
<script src="<?php echo $apiUrl; ?>&callback=initMap"></script>
<div id="map"
     style="height:<?php echo $block->getHeight(); ?>; width: <?php echo $block->getWidth(); ?>;"
     data-bind="scope: 'store_location'"></div>